# Dependabot configuration for automatic dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Keep Rust dependencies up to date
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    # Automatically open PRs for security updates
    open-pull-requests-limit: 10
    # Add labels to PRs
    labels:
      - "dependencies"
      - "rust"
    # Automatically rebase when conflicts occur
    rebase-strategy: "auto"
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Commit message prefix
    commit-message:
      prefix: "chore(deps)"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
