[package]
name = "gtd-mcp-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-mcp-sdk = "0.7.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
anyhow = "1"
uuid = { version = "1", features = ["v4"] }
async-trait = "0.1"
