name: Security Audit

on:
  # Run weekly on Monday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 1'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  security-audit:
    name: Weekly Security Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    
    - name: Install cargo-audit
      run: cargo install cargo-audit --locked
    
    - name: Run security audit
      run: cargo audit
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v8
      with:
        script: |
          const title = '🔒 Security Vulnerability Detected';
          const body = `A security vulnerability has been detected in the project dependencies.
          
          Please run \`cargo audit\` locally to see the details and update the affected dependencies.
          
          You can also view the [workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId}) for more information.`;
          
          // Check if an issue already exists
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'security',
            creator: 'github-actions[bot]'
          });
          
          if (issues.data.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'dependencies']
            });
          }
